<Project>
  <!-- inherit solution wide configuration -->
  <Import Project="../Directory.Build.props"/>

  <ItemGroup Condition="$(MSBuildProjectName.EndsWith('.Specs')) OR $(MSBuildProjectName.EndsWith('.Tests'))">
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
  </ItemGroup>
</Project>
